In [ ]:
# Questions 8 & 9 ; Chapter 11
''' #8
A certain calculating machine uses only the digits 0 and 1. It is supposed to
transmit one of these digits through several stages. However, at every stage,
there is a probability p that the digit that enters this stage will be changed
when it leaves and a probability q = 1−p that it won’t. Form a Markov chain
to represent the process of transmission by taking as states the digits 0 and 1.
What is the matrix of transition probabilities?
'''

''' #9
 For the Markov chain in Exercise 8, draw a tree and assign a tree measure
assuming that the process begins in state 0 and moves through two stages
of transmission. What is the probability that the machine, after two stages,
produces the digit 0 (i.e., the correct digit)? What is the probability that the
machine never changed the digit from 0? Now let p = .1. Using the program
MatrixPowers, compute the 100th power of the transition matrix. Interpret
the entries of this matrix. Repeat this with p = .2. Why do the 100th powers
appear to be the same?
'''

In [11]:
import numpy as np
## Notes:
## Generates 1 or 0
## Digits transmit several stages, w/ prob. of digit changing.
## Prob q= 1-p; no change

## States are State 0 or State 1
states = [0,1]

## Starting as 0, there is prob p that changes to 1, with prob q=1-p that it stays 0
## Starting as 1, there is prob p that changes to 0, with prob q=1-p that it stays 1

                    # 0, 1
# matrix = np.array([[ 1-p, p ], # 0
#                    [ p,  1-p]] # 1
#                  )

## Decision tree => Starts State 0
#       0            #Starting Stage 
#    0      1        #Stage1
# 0    1  0    1
#What is the probability that the machine never changed the digit from 0? Now let p = .1.
matrix_point1= np.array([[1-0.1, 0.1 ],[ 0.1,  1-0.1]])
print(matrix_point1)
print('---------')
## If the number never changes, this means that meand 0 -> 0 -> 0
## Which has the probability of 0.9*0.9*0.9
print(round(0.9*0.9*0.9,4))
print('---------')
## Using Matrix Power in order to execute 100 times.
p1_100 = np.linalg.matrix_power(matrix_point1, 100)
print(p1_100)
print('---------')
#Repeat this with p = .2.
matrix_point2= np.array([[1-0.2, 0.2 ],[ 0.2,  1-0.2]])
print(matrix_point2)
print(round(0.8*0.8*0.8,4))
print('---------')
## Using Matrix Power in order to execute 100 times.
p2_100 = np.linalg.matrix_power(matrix_point2, 100)
print(p2_100)
print('---------')
# The 100 power tests are the same because of the large numbers law, that after a large amount of executions the probabilites
# level out and stabilize with similar probabilites.

[[0.9 0.1]
 [0.1 0.9]]
---------
0.729
---------
[[0.5 0.5]
 [0.5 0.5]]
---------
[[0.8 0.2]
 [0.2 0.8]]
0.512
---------
[[0.5 0.5]
 [0.5 0.5]]
---------
