In [22]:
# 1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.

# My understanding is the pandas is built on top of numpy, with both meant for faster data processing with unique structures. 
# Pandas' main use case data analysis and manipulation with mulitple "layers" on your data (like labels) possible, while numpy is 
# lighter and focussed primarily on numeric data / fast calculations. Also, mulitple Pandas Data frames allow for the aggregation of multiple
# Series or Arrays into one labeled object.

# An example of the subtle differences between the two, showign pandas ability to label.
import numpy as np
import pandas as pd
# A numpy array:
nparray_test = np.array([5,10,15,20])
print(nparray_test)
# A Pandas Series
series_test1 = pd.Series([5,10,15,20])
print(series_test1.index.values)
series_test2 = pd.Series([5,10,15,20],index=["Five","Ten","Fifteen","Twenty"])
print(series_test2.index)
df = pd.DataFrame(series_test2)
print(df)

[ 5 10 15 20]
[0 1 2 3]
Index(['Five', 'Ten', 'Fifteen', 'Twenty'], dtype='object')
          0
Five      5
Ten      10
Fifteen  15
Twenty   20


In [27]:
# 2. What is the ndarray in numPy?
# A function within the numpy library to create an array with multiple dimensions, or essentially a matrix of value for working with.

In [26]:
# 3. Create a 1D array of numbers from 0 to 9 
# Desired Output: 
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1d = np.array(range(0,10))
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# 4. Extract all odd numbers from array1 
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_num = array1[array1 % 2 == 1]
print(odd_num)

[1 3 5 7 9]


In [51]:
# 5. Get the common items between a and  b  
# #input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# #Desired Output:
# array([2, 4])

common_vals = np.intersect1d(a, b)
common_vals

array([2, 4])

In [55]:
# 6. From array a remove all items present in array  b 
# #Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# #Desired Output:
# array([1,2,3,4])
result = a[~np.isin(a,b)]
result

array([1, 2, 3, 4])

In [65]:
# 7. Find out if iris has any missing values. 
# # Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

## COde 
nulls = np.isnan(iris)
np.unique(nulls)
#Only False Values no null / missing values.

array([False])